version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Installing dependencies..."
      # Add any other installation commands here

  build:
    commands:
      - echo "Building the PHP application..."
      # Add your build commands here (e.g., composer install, npm run build, etc.)

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'

